Added Hindi translation
PurpurMC/PurpurClient pull request #24
Opened 2022-10-26 07:03 UTC by pratik1424

2022-10-26 08:08 UTC, RealRONiN requested changes
Should've used Google Translate, Hindi is my second language so I know that requested changes are required to get the translations right.

2022-10-26 08:08 UTC, RealRONiN commented on src/main/resources/assets/purpurclient/lang/hi_in.json
> +    "purpurclient.options.mobs.tooltip": "Open mob options स्क्रीन",
Replace with "मोब्स विकल्प स्क्रीन खोलें".

2022-10-26 08:08 UTC, RealRONiN commented on src/main/resources/assets/purpurclient/lang/hi_in.json
> +    "purpurclient.title.singleplayer": "%s पर एकल खिलाड़ी",
Replace with "सिंगलप्लेयर पर %s".

2022-10-26 08:08 UTC, RealRONiN commented on src/main/resources/assets/purpurclient/lang/hi_in.json
> +    "purpurclient.title.multiplayer.lan": "मल्टीप्लेयर (%s LAN पर )",
Repalce "LAN" with "लैन".

2022-10-26 08:08 UTC, RealRONiN commented on src/main/resources/assets/purpurclient/lang/hi_in.json
> +    "purpurclient.options.on": "%s: \u00a7aON",
Replace "ON" with "चालू".

2022-10-26 09:18 UTC, pratik1424 commented
Hey @RealRONiN,
Thank you so much for the suggestions, I have made all the necessary corrections. 
Let me know if you find more.

2022-10-26 09:25 UTC, RealRONiN approved these changes
Looks good to me.

2022-10-30 19:43 UTC, pratik1424 commented
@BillyGalbreath Any updates on this PR?

2022-10-30 21:22 UTC, granny approved these changes

2022-10-30 21:22 UTC, merged